// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-CZA_lr7XfEMLEGOr7GW6yhr6mIdXxI',
    appId: '1:82193881679:web:d3d041f116c9062de4a83a',
    messagingSenderId: '82193881679',
    projectId: 'mynotes-kiran-flutter-project',
    authDomain: 'mynotes-kiran-flutter-project.firebaseapp.com',
    storageBucket: 'mynotes-kiran-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFvSTvJMFrSCFKkOM4giCaykmQoJUMbc',
    appId: '1:82193881679:android:acf215bfc0229239e4a83a',
    messagingSenderId: '82193881679',
    projectId: 'mynotes-kiran-flutter-project',
    storageBucket: 'mynotes-kiran-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt_-Qzd54IROfW8uR3JkUqAQeiUtQG4mM',
    appId: '1:82193881679:ios:f43e3de117933d3ce4a83a',
    messagingSenderId: '82193881679',
    projectId: 'mynotes-kiran-flutter-project',
    storageBucket: 'mynotes-kiran-flutter-project.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt_-Qzd54IROfW8uR3JkUqAQeiUtQG4mM',
    appId: '1:82193881679:ios:023b4a23e6a28121e4a83a',
    messagingSenderId: '82193881679',
    projectId: 'mynotes-kiran-flutter-project',
    storageBucket: 'mynotes-kiran-flutter-project.appspot.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
